---
title: "Communities Speak"
date: "01/2024"
output:
  html_document: default
  pdf_document: default
---

## Notebook Setup
```{r message=FALSE, warning=FALSE}
# Load packages
library(googledrive)
library(readxl)
library(tidyverse)
library(stringr)
library(haven)
library(rjson)
library(googlesheets4)

# Set working directory
# setwd("~/Documents/GitHub/repo/fa23")
setwd("~/Columbia/Communities Speak/Survey-Analysis-Repository/fa23")

# Read in custom functions
source("code/functions/make_codebook.R")
source("code/default_setup.R")
```

## Load data
```{r message=FALSE, warning=FALSE}
# Load Rdata
survey6 <- readRDS("../data/processed/cleaned.rds")

# Load boroughs zipcode data from input folder
boroughs <- read_csv("../data/input/boroughs.csv") %>% distinct

# Bring in borough + neighborhood to survey data
wrangled <- survey6 %>%
  mutate(zip = as.numeric(substr(zip, 1, 5))) %>% 
  left_join(boroughs, by = "zip")

wrangled <- wrangled %>% mutate(gc = 99, distributionchannel = 99)

# Calculate completion rate
wrangled <- wrangled %>% 
  mutate(completion = rowSums(!is.na(wrangled))/ncol(wrangled))
```

## Clean up "Other" categories
```{r, eval=FALSE}
#### WIP ####
# Locate ID for the Google Sheets file in the Drive for the "Other" mapping info
gs4_found <- gs4_find()
mapping_id <- gs4_found %>% filter(str_detect(name, "other_mapping_fa23")) %>% 
  select(id, name)

mapping_gen <- read_sheet(mapping_id$id, sheet = "Gender") %>%
  rename_all(stringr::str_to_lower) %>%
  mutate_if(is.character, stringr::str_to_lower)

mapping_ori <- read_sheet(mapping_id$id, sheet = "Sexual Orientation") %>%
  rename_all(stringr::str_to_lower) %>%
  mutate_if(is.character, stringr::str_to_lower)

mapping_edu <- read_sheet(mapping_id$id, sheet = "Education") %>%
  rename_all(stringr::str_to_lower) %>%
  mutate_if(is.character, stringr::str_to_lower)

mapping_rel <- read_sheet(mapping_id$id, sheet = "Religion") %>%
  rename_all(stringr::str_to_lower) %>%
  mutate_if(is.character, stringr::str_to_lower)

mapping_race <- read_sheet(mapping_id$id, sheet = "Race") %>%
  rename_all(stringr::str_to_lower) %>%
  mutate_if(is.character, stringr::str_to_lower)

mapping_lang <- read_sheet(mapping_id$id, sheet = "Language") %>%
  rename_all(stringr::str_to_lower) %>%
  mutate_if(is.character, stringr::str_to_lower)

wrangled_test <- wrangled %>%
  left_join(mapping_gen, by = "gen_text") %>%
  left_join(mapping_ori, by = "sex_text") %>%
  left_join(mapping_edu, by = "sch_level_text") %>%
  left_join(mapping_rel, by = "relig_text") %>%
  left_join(mapping_race, by = "race_text") %>%
  left_join(mapping_lang, by = "lang_text")

wrangled_test <- wrangled_test %>% mutate(
  gender = labelled::to_character(gen),
  gender_cleaned = ifelse(gender == "other" & !is.na(gender_cleaned), gender_cleaned, gender),
  sex_orientation = labelled::to_character(sex),
  sex_orientation_cleaned = ifelse(sex_orientation == "something else, please specify" & !is.na(sex_orientation_cleaned), sex_orientation_cleaned, sex_orientation),
  edu_cat = labelled::to_character(sch_level),
  edu_cat_cleaned = ifelse(edu_cat == "other" & !is.na(edu_cat_cleaned), edu_cat_cleaned, edu_cat),
  religion = labelled::to_character(relig),
  religion_cleaned = ifelse(religion == "other" & !is.na(religion_cleaned), religion_cleaned, religion)
  )
```


## Create Demographic variables
```{r}
# Create gender + sexual orientation text variable
wrangled <- wrangled %>%
  mutate(gender = labelled::to_character(gen),
         sex_orientation = labelled::to_character(sex))

# Create religion text variable
wrangled <- wrangled %>%
  mutate(religion = labelled::to_character(relig)) %>%
  mutate(religion_group = ifelse(relig %in% c(1, 2), "Christian",
                          ifelse(relig %in% c(3, 4, 5), "Minority (Jewish, Muslim, Hindu)",
                          ifelse(relig == 6, "Other",
                          ifelse(relig == 7, "None/Unaffiliated", NA)))))

# Create LGBTQIA+ indicator
wrangled <- wrangled %>%
  mutate(lgbtq_bi = ifelse((gen %in% c(4,5,7) | sex %in% c(2,3,4,6)), 1,
                    ifelse(!is.na(gen) | !is.na(sex), NA, 0)),
         lgbtq = ifelse(lgbtq_bi == 1, "LGBTQIA+", "Not LGBTQIA+"))

# Create binary for all of the boroughs
wrangled <- wrangled %>% mutate(
  bronx_bi = borough == "bronx",
  brooklyn_bi = borough == "brooklyn",
  queens_bi = borough == "queens",
  manhattan_bi = borough == "manhattan",
  staten_island_bi = borough == "staten island")

# Create text indicator for language spoken at home
wrangled <- wrangled %>% mutate(
  english_lang = ifelse(lang == 0, "English spoken at home",
                 ifelse(lang == 1, "Other langugage spoken at home", NA)))
    
# Create race variables
wrangled <- wrangled %>% mutate(
  # Create binary for asian
  asian = ifelse(race_e_asian == 1 | race_s_asian == 1, 1, 0),
  # Categorize race according to Census
  race_census = ifelse(race != "white (non-hispanic or latinx)",
                       str_replace_all(race, 
                                       c(".*hispanic or latinx.*" = "hispanic or latinx",
                                         ".*;.*" = "two or more races",
                                         "prefer not to answer" = NA_character_)),
                       "white (non-hispanic or latinx)"),
  race_census2 = ifelse(str_detect(race_census, "asian"), "asian", race_census),
  race_census3 = ifelse(str_detect(race, ";"), "two or more races",
                 ifelse(str_detect(race, "asian"), "asian", race_census)))

# Modify values of existing household variables based on manual observations
wrangled <- wrangled %>% mutate(
  # Calculate household size
  hh_size = hh_ch_0_2 + hh_ch_3_5 + hh_ch_6_17 + hh_ad_18_64 + hh_sn_65,
  # Correct household variables when hh_size = 0 according to age of respondent
  hh_ad_18_64 = ifelse(hh_ad_18_64 + hh_sn_65 == 0 & age >= 18 & age <= 64, 1, hh_ad_18_64),
  hh_sn_65 = ifelse(hh_ad_18_64 + hh_sn_65 == 0 & age > 64, 1, hh_sn_65)
)

# Modify rows when age is entered instead of household size
# Define manual updates
updated_rows <- tibble(responseid = c("r_1hxpashwn3h89pu", "r_xfngrrgjoxvtmnv", "r_5aqdmcubgpt73k5"),
                       hh_sn_65 = c(1, 0, 1),
                       hh_ad_18_64 = c(0, 2, 1),
                       hh_ch_6_17 = c(0, 1, 1),
                       hh_ch_3_5 = c(0, 1, 1),
                       hh_ch_0_2 = c(0, 1, 0))

wrangled <- rows_update(wrangled, updated_rows, by = "responseid")

# Create household variables
wrangled <- wrangled %>% mutate(
  # Recalculate household size
  hh_size = hh_ch_0_2 + hh_ch_3_5 + hh_ch_6_17 + hh_ad_18_64 + hh_sn_65,
  # Create binary variables for different types of people in the household
  hh_ad_one = hh_sn_65 + hh_ad_18_64 == 1,
  hh_sn_65_bi = hh_sn_65 >= 1,
  hh_ch_6_17_bi = hh_ch_6_17 >= 1,
  hh_ch_3_5_bi = hh_ch_3_5 >= 1,
  hh_ch_0_2_bi = hh_ch_0_2 >= 1,
  hh_ch_0_17_bi = if_any(c(hh_ch_6_17, hh_ch_3_5, hh_ch_0_2), ~. >= 1),
  hh_ch_sn = if_all(c(hh_sn_65_bi, hh_ch_0_17_bi), ~. >= 1)
  ) %>% mutate(
    # Create text indicators
    hh_child = ifelse(hh_ch_0_17_bi == 0, "No children in household",
               ifelse(hh_ch_0_17_bi == 1, "Has children in household", NA)),
    hh_elderly = ifelse(hh_sn_65_bi == 0, "No senior citizens in household", 
                 ifelse(hh_sn_65_bi == 1, "Has senior citizens in household", NA))
  )

# Create binary variables for disabilities
wrangled <- wrangled %>% mutate(
  dis = disab_cog == 1 | disab_phys == 1,
  cog_dis = disab_cog == 1,
  phys_dis = disab_phys == 1,
  both_dis = disab_cog == 1 & disab_phys == 1
  ) %>% mutate(
    hh_disability = ifelse(dis == 0, "Household with no disability",
                    ifelse(dis == 1, "Household with a disability", NA))
  )
  

# Create education variables
wrangled <- wrangled %>% mutate(
  edu_cat = labelled::to_character(sch_level),
  # Determine level of educational attainment
  sch_level_cat = case_when(
    str_detect(edu_cat, "high school|some college|ass") ~ as.numeric(sch_level),
    str_detect(edu_cat, "bach") ~ 5,
    str_detect(edu_cat, "doct|mast|prof") ~ 6),
  # Create binary for bachelor's degree attainment
  sch_bach = ifelse(sch_level_cat <= 4, 0, 1),
  education = ifelse(sch_level_cat <= 4, "Less than Bachelor's",
              ifelse(sch_level_cat <= 6, "Bachelor's or Higher", NA))
  )

# Create income variables
wrangled <- wrangled %>% mutate(
  # Create binary for direction of income change
  inc_neg = ifelse(inc_ch == 2, 1, 0),
  inc_pos = ifelse(inc_ch == 1, 1, 0),
  inc_same = ifelse(inc_ch == 3, 1, 0),
  # Create binary to indicate below poverty line
  below_poverty_bi = ifelse(income == 1 | income == 2 |
                              income == 3 & hh_ad_18_64 == 1 & hh_ch_6_17 + hh_ch_3_5 + hh_ch_0_2 >= 1 | 
                              income == 3 & hh_ad_18_64 == 1 & hh_sn_65 >= 1 | 
                              income == 3 & hh_ad_18_64 > 1 & hh_ch_6_17 + hh_ch_3_5 + hh_ch_0_2 == 0 | 
                              income == 3 & hh_ad_18_64 > 1 & hh_sn_65 == 0 | 
                              income == 4 & hh_ad_18_64 == 1 & hh_sn_65 >= 1 | 
                              income == 4 & hh_ad_18_64  == 1 & hh_ch_6_17 + hh_ch_3_5 + hh_ch_0_2 + hh_sn_65 >= 3 & hh_sn_65 >= 1 |
                              income == 4 & hh_ad_18_64 == 1 & hh_ch_6_17 + hh_ch_3_5 + hh_ch_0_2 + hh_sn_65 >= 4 & hh_ch_6_17 + hh_ch_3_5 + hh_ch_0_2 >= 3 | 
                              income == 4 & hh_ad_18_64 == 2 &  hh_ch_6_17 + hh_ch_3_5 + hh_ch_0_2 + hh_sn_65 >= 2 | 
                              income == 4 & hh_ad_18_64 >= 3, 1, 0),
  # Create indicator for income level
  inc_dist = case_when(
    income == 1 | income == 2 ~ 1,
    income == 3 ~ 2,
    TRUE ~ 3),
  inc_ab_med = income == 4 | income == 5,
  inc_be_med = income == 1 | income == 2 | income == 3,
  ) %>% mutate(
  # Create text indicators
  inc_level = ifelse(inc_dist == 1, "HH income below $36500",
              ifelse(inc_dist == 2, "HH income between $36500 and $69500",
              ifelse(inc_dist == 3, "HH income above $69500", NA))),
  below_poverty = ifelse(below_poverty_bi == 0, "Above Poverty Level", 
                  ifelse(below_poverty_bi == 1, "Below Poverty Level", NA)),
  below_median = ifelse(inc_be_med == 0, "Above Median Income", 
                 ifelse(inc_be_med == 1, "Below Median Income", NA))
)

# Create employment variables
wrangled <- wrangled %>% mutate(
  # Create binary for in-person work
  wrk_in = wrk %in% c(1, 2, 3),
  # Determine change in employment status
  emp_status_before = case_when(
    str_detect(emp_before, "unemp") ~ "unemployed",
    str_detect(emp_before, "full|part|free|gig|small|home") ~ "employed",
    str_detect(emp_before, "student") ~ "student",
    str_detect(emp_before, ";") ~ "multiple_other",
    TRUE ~ emp_before),
  emp_status_after = case_when(
    str_detect(emp_after, "unemp") ~ "unemployed",
    str_detect(emp_after, "full|part|free|gig|small|home") ~ "employed",
    str_detect(emp_after, "student") ~ "student",
    str_detect(emp_after, ";") ~ "multiple_other",
    TRUE ~ emp_after),
  emp_change = emp_before != emp_after,
  # Determine change in part-time employment
  emp_before_part_time = case_when(
    emp_before_un == 0 & any(emp_before_ft == 1, emp_before_pt == 1, emp_before_fl == 1) ~ 1,
    emp_before_un == 1 ~ 0),
  emp_after_part_time = case_when(
    emp_after_un == 0 & any(emp_after_ft == 1, emp_after_pt == 1, emp_after_fl == 1) ~ 1,
    TRUE ~ 0))
```

## Create Policy variables
```{r}
# Create binary for discrimination and violence
wrangled <- wrangled %>% mutate(
  # Concerned about discrimination
  discrim_bi = discrim %in% c(1, 2),
  # Experienced abuse or violence
  exp_ab_or_vi = str_detect(exp, "yes"),
  # Experienced abuse AND violence
  exp_ab_and_vi = str_detect(exp, "verbal abuse") & str_detect(exp, "physical violence"))

# Create binary variables for ratings of government services
wrangled <- wrangled %>% mutate(
  # Binary for good and bad gov services
  across(c(rate_neigh_pub, rate_neigh_rec, rate_neigh_code, rate_neigh_pol, rate_neigh_pre), ~ . < 3, .names = "{.col}_good"),
    across(c(rate_neigh_pub, rate_neigh_rec, rate_neigh_code, rate_neigh_pol, rate_neigh_pre), ~ . > 3, .names = "{.col}_bad"),
  # Binary for good and bad gov's response to COVID-19
  rate_gov_bad = rate_gov == 4 | rate_gov == 5,
  rate_gov_good = rate_gov < 3)

# Create health variables
wrangled <- wrangled %>% mutate(
  stress_score = rowSums(across(starts_with("stress_"))),
  # Comparison of stress level to average
  stress_bi = mean(stress_score, na.rm = TRUE) < stress_score,
  # Binary for insurance ownership
  ins_has = ins_none == 0)

# Create binary variables for help resources
wrangled <- wrangled %>% mutate(
  lr_fam = if_any(starts_with("lr_") & ends_with("ff"), ~.==1),
  lr_gov = if_any(starts_with("lr_") & ends_with("gov"), ~.==1),
  lr_fb = if_any(starts_with("lr_") & ends_with("fb"), ~.==1),
  lr_np = if_any(starts_with("lr_") & ends_with("np"), ~.==1),
  lr_uni = if_any(starts_with("lr_") & ends_with("uni"), ~.==1),
  lr_emp = if_any(starts_with("lr_") & ends_with("emp"), ~.==1))

# Create binary variables for insecurity measures
wrangled <- wrangled %>% mutate(
  food_insec = ifelse(is.na(diff_afford_food) & is.na(diff_access_food), NA,
                      if_any(c(diff_afford_food, diff_access_food), ~. == 1 & !is.na(.))),
  house_insec = ifelse(is.na(diff_afford_rent) & is.na(diff_access_hous), NA,
                       if_any(c(diff_afford_rent, diff_access_hous), ~. == 1 & !is.na(.))),
  fin_insec = if_any(c(diff_afford_food, diff_afford_util, diff_afford_rent), ~. == 1), # all from the same Qs
  res_insec = if_any(c(diff_access_food, diff_access_ss, diff_access_trans, diff_access_hous, diff_access_internet), ~. == 1), # all from the same Qs
  # severe measures
  sev_food_insec = ifelse(food_insec == 1 & insecure_food_ran_out == 1 | food_insec == 1 & insecure_food_worr == 1, 1,
                   ifelse(!is.na(food_insec) & (!is.na(insecure_food_ran_out) | !is.na(insecure_food_ran_out)), 0, NA)),
  sev_house_insec = ifelse(house_insec == 1 & insecure_hous == 1 | house_insec == 1 & insecure_evict == 1, 1,
                    ifelse(!is.na(house_insec) & (!is.na(insecure_hous) | !is.na(insecure_evict)), 0, NA)))
```

## Save data
```{r}
saveRDS(wrangled, file = "../data/output/wrangled.rds")
write_csv(wrangled, file = "../data/output/wrangled.csv", na = "")
wrangled_data_upload <- drive_upload(
    media = "../data/output/wrangled.csv",
    path = as_id("https://drive.google.com/drive/folders/1y8cgf5lY6kxtw-Vvs4NI3aQ3TRt9rfoF"),
    name = "wrangled",
    overwrite = TRUE,
    type = "spreadsheet"
  )

sheet_rename(wrangled_data_upload$id, new_name = "Sheet1")
```